language: go
go: 1.10.x
sudo: required
dist: trusty
os:
  - linux
  - osx
env:
  global:
    - CGO_ENABLED: 0
  matrix:
    - POSTGRESQL_VERSION=9.2
    - POSTGRESQL_VERSION=9.3
    - POSTGRESQL_VERSION=9.4
    - POSTGRESQL_VERSION=9.5
    - POSTGRESQL_VERSION=9.6
    - POSTGRESQL_VERSION=10
    - RABBITMQ_VERSION=any
matrix:
  fast_finish: true
  exclude:
    - os: linux
      env: POSTGRESQL_VERSION=10
    - os: osx
      env: POSTGRESQL_VERSION=9.2
    - os: osx
      env: POSTGRESQL_VERSION=9.3
jobs:
  include:
    - stage: deploy
      sudo: false
      if: tag IS present
      script:
        - go get github.com/mitchellh/gox
        - CGO_ENABLED=0 gox -osarch="linux/amd64 darwin/amd64 windows/amd64" -ldflags="-s -w"
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file_glob: true
        file: ci-tricks_*
        on:
          tags: true
