language: go
sudo: required
dist: trusty
os:
  - linux
  - osx
env:
  matrix:
    - POSTGRESQL_VERSION=9.2
    - POSTGRESQL_VERSION=9.3
    - POSTGRESQL_VERSION=9.4
    - POSTGRESQL_VERSION=9.5
    - POSTGRESQL_VERSION=9.6
    - POSTGRESQL_VERSION=10
matrix:
  fast_finish: true
  exclude:
    - os: linux
      env: POSTGRESQL_VERSION=10
    - os: osx
      env: POSTGRESQL_VERSION=9.2
    - os: osx
      env: POSTGRESQL_VERSION=9.3
