language: go
sudo: required
dist: trusty
os:
  - linux
  - osx
env:
  global:
    - CGO_ENABLED: 0
  matrix:
    - POSTGRESQL_VERSION=9.2
    - POSTGRESQL_VERSION=9.3
    - POSTGRESQL_VERSION=9.4
    - POSTGRESQL_VERSION=9.5
    - POSTGRESQL_VERSION=9.6
    - POSTGRESQL_VERSION=10
    - RABBITMQ_VERSION=any
matrix:
  fast_finish: true
  exclude:
    - os: linux
      env: POSTGRESQL_VERSION=10
    - os: osx
      env: POSTGRESQL_VERSION=9.2
    - os: osx
      env: POSTGRESQL_VERSION=9.3
