
[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"
